<!-- @author suzilin -->
<!-- @email zilinsu@yangqianguan.com -->
<!-- @date 2021-05-07 16:24:16.499 -->
<!-- @desc generated by yqg-cli@5.0.7 -->

<template>

    <div class="xxx">
        xxx
    </div>

</template>

<script type="text/babel">

    export default {
        name: 'xxx'
    };

</script>

<style lang="scss" rel="stylesheet/scss" scoped>

    .xxx {
        color: red;
    }

</style>
